[build]
    base = "truffle-clone"
    command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"
